version: "2"

services:
  styleguide:
    build: .
    ports:
      - "3005:8080"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./build:/opt/gulp/build
      - ./styleguide:/opt/gulp/styleguide
      - ./src:/opt/gulp/src
      - ./existsInS3.js:/opt/gulp/existsInS3.js
      - ./gulpfile.js:/opt/gulp/gulpfile.js
      - ./kss-config.json:/opt/gulp/kss-config.json
      - ./package.json:/opt/gulp/package.json
    command: "npm start"
