version: '2'
services:
  styleguide:
    image: woorank/woorank-theme
    build: .
    ports:
      - "3005:8080"
      - "35729:35729"
    volumes:
      - ./styleguide:/opt/gulp/styleguide
      - ./woo-components:/opt/gulp/woo-components
      - ./src:/opt/gulp/src
      - ./testVersion.js:/opt/gulp/testVersion.js
      - ./gulpfile.js:/opt/gulp/gulpfile.js
      - ./kss-config.json:/opt/gulp/kss-config.json
      - ./awsConfig.json:/opt/gulp/awsConfig.json
      - ./package.json:/opt/gulp/package.json
    command: "npm start"
