version: 2
jobs:
  build:
    machine:
       docker_layer_caching: false
    steps:
      - checkout
      - run: docker-compose build
      - run: docker-compose run styleguide npm run build

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [[ "${CIRCLE_BRANCH}" =~ dryrun_.* ]]; then
              docker-compose run styleguide npm run deploy
            fi

      - deploy:
          command: |
            export PACKAGE_EXISTS="$(npm info woorank-theme@$(npm run -s version) version)"
            echo "Existing version: ${PACKAGE_EXISTS}"
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ ! "${PACKAGE_EXISTS}" == "undefined" ]; then
              echo "Publishing..."
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish
            fi
