var countries = {
  'flag-int': 'Global (Google.com)',
  'flag-ae': 'United Arab Emirates (English)',
  'flag-ar': 'Argentina',
  'flag-at': 'Austria',
  'flag-au': 'Australia',
  'flag-be': 'Belgium',
  'flag-bg': 'Bulgaria',
  'flag-br': 'Brazil',
  'flag-ca': 'Canada',
  'flag-ch': 'Switzerland',
  'flag-cl': 'Chile',
  'flag-co': 'Colombia',
  'flag-cy': 'Cyprus',
  'flag-cz': 'Czech Republic',
  'flag-de': 'Germany',
  'flag-dk': 'Denmark',
  'flag-ec': 'Ecuador',
  'flag-ee': 'Estonia',
  'flag-eg': 'Egypt',
  'flag-es': 'Spain',
  'flag-et': 'Ethiopia',
  'flag-fi': 'Finland',
  'flag-fr': 'France',
  'flag-ge': 'Georgia',
  'flag-gr': 'Greece',
  'flag-gt': 'Guatemala',
  'flag-hk': 'Hong Kong',
  'flag-hr': 'Croatia',
  'flag-id': 'Indonesia',
  'flag-ie': 'Ireland',
  'flag-il': 'Israel',
  'flag-in': 'India',
  'flag-it': 'Italy',
  'flag-jp': 'Japan',
  'flag-lt': 'Lithuania',
  'flag-kh': 'Cambodia',
  'flag-lu': 'Luxembourg',
  'flag-ma': 'Morocco',
  'flag-mx': 'Mexico',
  'flag-my': 'Malaysia',
  'flag-nl': 'Netherlands',
  'flag-no': 'Norway',
  'flag-nz': 'New Zealand',
  'flag-pe': 'Peru',
  'flag-ph': 'Philippines',
  'flag-pl': 'Poland',
  'flag-pt': 'Portugal',
  'flag-ro': 'Romania',
  'flag-rs': 'Serbia',
  'flag-ru': 'Russia',
  'flag-se': 'Sweden',
  'flag-sg': 'Singapore',
  'flag-sk': 'Slovakia',
  'flag-th': 'Thailand',
  'flag-tr': 'Turkey',
  'flag-tw': 'Taiwan',
  'flag-ua': 'Ukraine',
  'flag-uk': 'United Kingdom',
  'flag-us': 'United States',
  'flag-uy': 'Uruguay',
  'flag-ve': 'Venezuela',
  'flag-vn': 'Vietnam',
  'flag-za': 'South Africa'
};

module.exports.register = function (handlebars) {
  handlebars.registerHelper('flag', function (inputA) {
    return new handlebars.SafeString(countries[inputA] + ': #' + inputA);
  });
};
